/// Known browser hijacker search engine and homepage URLs.
/// If a browser's homepage or default search engine contains any of these,
/// it's been hijacked.
pub static HIJACKER_SEARCH_DOMAINS: &[(&str, &str)] = &[
    // Search hijackers
    ("trovi.com", "Trovi search hijacker"),
    ("conduit.com", "Conduit search hijacker"),
    ("search.conduit.com", "Conduit search hijacker"),
    ("babylon.com", "Babylon search hijacker"),
    ("search.babylon.com", "Babylon search hijacker"),
    ("delta-search.com", "Delta search hijacker"),
    ("delta-homes.com", "Delta Homes hijacker"),
    ("isearch.omiga-plus.com", "Omiga Plus hijacker"),
    ("safefinder.com", "SafeFinder hijacker"),
    ("search.safefinder.com", "SafeFinder hijacker"),
    ("istartsurf.com", "iStartSurf hijacker"),
    ("webssearches.com", "WebsSearches hijacker"),
    ("golsearch.com", "GolSearch hijacker"),
    ("mystartsearch.com", "MyStartSearch hijacker"),
    ("yoursearching.com", "YourSearching hijacker"),
    ("dosearches.com", "DoSearches hijacker"),
    ("qvo6.com", "Qvo6 hijacker"),
    ("snapdo.com", "Snap.do hijacker"),
    ("search.snapdo.com", "Snap.do hijacker"),
    ("searchgol.com", "SearchGol hijacker"),
    ("sweet-page.com", "Sweet Page hijacker"),
    ("v9.com", "V9 search hijacker"),
    ("search.ask.com", "Ask Toolbar hijacker"),
    ("home.mywebsearch.com", "MyWebSearch hijacker"),
    ("search.mywebsearch.com", "MyWebSearch hijacker"),
    ("mindspark.com", "MindSpark hijacker"),
    ("search.iminent.com", "Iminent hijacker"),
    ("start.iminent.com", "Iminent hijacker"),
    ("searchult.com", "Searchult hijacker"),
    ("search.certified-toolbar.com", "Certified Toolbar hijacker"),
    ("portaldosites.com", "Portal do Sites hijacker"),
    ("nationzoom.com", "NationZoom hijacker"),
    ("awesomehp.com", "AwesomeHP hijacker"),
    // Fake search engines
    ("searchmarquis.com", "Search Marquis (Mac hijacker on Windows)"),
    ("searchbaron.com", "Search Baron hijacker"),
    ("mybrowser-search.com", "MyBrowser Search hijacker"),
    ("searchitnow.info", "SearchItNow hijacker"),
    ("chumsearch.com", "Chum Search hijacker"),
    ("nearbyme.io", "NearbyMe hijacker"),
    ("searchmine.net", "SearchMine hijacker"),
    // Scareware homepages
    ("your-pc-is-infected", "Scareware fake homepage"),
    ("computer-has-virus", "Scareware fake homepage"),
    ("virus-alert-", "Scareware fake homepage"),
    ("windows-error-", "Scareware fake homepage"),
];

/// Known legitimate search engines — anything else in browser settings is suspicious
pub static LEGITIMATE_SEARCH_ENGINES: &[&str] = &[
    "google.com",
    "google.co.nz",
    "google.co.uk",
    "bing.com",
    "duckduckgo.com",
    "yahoo.com",
    "ecosia.org",
    "brave.com/search",
    "startpage.com",
    "qwant.com",
    "search.brave.com",
    "yandex.com",
    "baidu.com",
];
